services:
  lendsqr:
    depends_on:
      - db
    container_name: lendsqr
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "6000:6000"

  db:
    image: mysql:8.0-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_AUTHENTICATION_PLUGIN: password
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - web

  adminer:
    image: adminer
    ports:
      - "8032:8080"
    networks:
      - web
    


volumes:
  mysql_data:


networks:
  web:
