services:
  lendsqr:
    depends_on:
      - db
    container_name: lendsqr
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_AUTHENTICATION_PLUGIN: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - web

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - web
    


volumes:
  mysql_data:


networks:
  web: